
services:
  postgres-post:
    image: postgres:latest
    environment:
      POSTGRES_DB: post_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-post-data:/var/lib/postgresql/data

  postgres-user:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"

  post-service:
    build: ./post-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-post
      - redis
      - kafka
      - service-discovery
      - zipkin

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-user
      - kafka
      - service-discovery
      - zipkin

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
      - zipkin

volumes:
  postgres-post-data:
  postgres-user-data:
