server:
  port: 8082

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

logging:
  level:
    root: info